DWAPlannerROS:
  # Robot Configuration Parameters

  #x方向最大线速度绝对值，单位:米/秒
  #x方向最小线速度绝对值，单位:米/秒。如果为负值表示可以后退.
  max_vel_x: 0.5
  min_vel_x: -0.1

  #y方向最大线速度绝对值，单位:米/秒。差分驱动机器人为0
  #y方向最小线速度绝对值，单位:米/秒。差分驱动机器人为0
  max_vel_y: 0.0
  min_vel_y: 0.0

  # The velocity when robot is moving in a straight line

  #机器人最大平移速度的绝对值，单位为 m/s
  #机器人最小平移速度的绝对值，单位为 m/s
  #机器人被认属于“停止”状态时的平移速度。如果机器人的速度低于该值，则认为机器人已停止。单位为 m/s
  max_trans_vel: 0.22
  min_trans_vel: 0.13
  # trans_stopped_vel: 0.05

  #机器人的最大旋转角速度的绝对值，单位为 rad/s
  #机器人最小平移速度的绝对值，单位为 m/s
  #机器人被认属于“停止”状态时的旋转速度。单位为 rad/s
  max_rot_vel: 1.82
  min_rot_vel: 0.9
  # rot_stopped_vel: 0.05

  #机器人在x方向的极限加速度，单位为 meters/sec^2
  #机器人在y方向的极限加速度，单位为 meters/sec^2
  #机器人的极限旋转加速度，单位为 rad/sec^2
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  # Goal Tolerance Parametes 目标距离公差参数
  #注：这三个参数的设置及影响讨论请参考《ROS导航功能调优指南》

  #到到目标点时，控制器在x和y方向上的容差（tolerence）（米）。即：到达目标点时,在xy平面内与目标点的距离误差
  xy_goal_tolerance: 0.05
  #到达目标点时，控制器在偏航/旋转时的弧度容差(tolerance)。即：到达目标点时偏行角允许的误差，单位弧度
  yaw_goal_tolerance: 0.17
  # 设置为true时表示：如果到达容错距离内,机器人就会原地旋转；即使转动是会跑出容错距离外。
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters 前向模拟参数
  #前向模拟轨迹的时间，单位为s(seconds)
  sim_time: 2.0
  #x方向速度空间的采样点数.
  vx_samples: 20
  #y方向速度空间采样点数,差分驱动机器人y方向永远只有1个值（0.0）
  vy_samples: 0
  #旋转方向的速度空间采样点数.
  vth_samples: 40
  controller_frequency: 10.0

  # Trajectory Scoring Parameters 轨迹评分参数
  #控制器与给定路径接近程度的权重
  path_distance_bias: 32.0
  #控制器与局部目标点的接近程度的权重，也用于速度控制
  goal_distance_bias: 20.0
  #控制器躲避障碍物的程度
  occdist_scale: 0.02
  #以机器人为中心，额外放置一个计分点的距离
  forward_point_distance: 0.325
  #机器人在碰撞发生前必须拥有的最少时间量。该时间内所采用的轨迹仍视为有效。即：为防止碰撞,机器人必须提前停止的时间长度
  stop_time_buffer: 0.2
  #开始缩放机器人足迹时的速度的绝对值，单位为m/s。
  #在进行对轨迹各个点计算footprintCost之前，会先计算缩放因子。如果当前平移速度小于scaling_speed，则缩放因子为1.0，
  #否则，缩放因子为(vmag - scaling_speed) / (max_trans_vel - scaling_speed) * max_scaling_factor + 1.0。
  #然后，该缩放因子会被用于计算轨迹中各个点的footprintCost。
  #参考：https://www.cnblogs.com/sakabatou/p/8297479.html
  #亦可简单理解为：启动机器人底盘的速度.(Ref.: https://www.corvin.cn/858.html)
  scaling_speed: 0.25
  #最大缩放因子。max_scaling_factor为上式的值的大小。
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters 振荡预防参数
  #机器人必须运动多少米远后才能复位震荡标记(机器人运动多远距离才会重置振荡标记)
  oscillation_reset_dist: 0.05

  # Debugging 调试参数
  #将规划的轨迹在RVIZ上进行可视化
  publish_traj_pc: true
  #将代价值进行可视化显示
  #是否发布规划器在规划路径时的代价网格.如果设置为true,那么就会在~/cost_cloud话题上发布sensor_msgs/PointCloud2类型消息.
  publish_cost_grid_pc: true
