# 全局代价地图配置
global_costmap:
   # “global_frame”参数定义了代价地图应该运行的坐标系，在这种情况下，我们将选择/map坐标系。
   # 对于全局代价地图，我们用map框架来作为global框架。
   global_frame: /map

   # “robot_base_frame”参数定义了代价地图应该为机器人的基座的坐标系。
   # 这个通常不是base_link就是base_footprint。对于turtlebot应设为base_footprint。
   robot_base_frame: /base_footprint

   # “update_frequency”参数决定了代价地图更新的频率（以Hz为单位）。根据传感器数据，全局地图更新的频率，
   # 这个数值越大，你的计算机的CPU负担会越重，特别对于全局地图，通常设定一个相对较小、在1.0到5.0之间的值。
   update_frequency: 10.0   
   publish_frequency: 10.0
   # “static_map”参数确定是否由map_server提供的地图服务来进行代价地图的初始化。如果您没有使用现有的地图或地图服务器，
   # 请将static_map参数设置为false。当本地地图需要根据传感器数据动态更新的时候，我们通常会把这个参数设为false。
   static_map: true

   # rolling_window: false
   # resolution: 0.01
   transform_tolerance: 0.5 #1.0
   # map_type: costmap
