# 本地代价地图配置
local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 10.0 #3.0
   # “publish_frequency”参数确定代价地图发布可视化信息的速率（以Hz为单位）
   publish_frequency: 10.0 #1.0
   static_map: false

   # 将“rolling_window”参数设置为true意味着当机器人移动时，保持机器人在本地代价地图中心。
   # “宽度”，“高度”和“分辨率”参数设置本地代价地图（滑动地图）的宽度（米），高度（米）和分辨率（米/单元格）。
   # 请注意，这个网格的分辨率与静态地图的分辨率不同，但大多数时候我们倾向设置为相同值。
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 0.5
   # map_type: costmap
